# Generated by Django 2.2 on 2021-03-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_remove_aluno_cpf'),
        ('validacpfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacpf',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno'),
            preserve_default=False,
        ),
    ]
