# Generated by Django 2.2 on 2021-03-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacpfs', '0002_validacpf_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacpf',
            name='aluno',
        ),
    ]
