# Generated by Django 2.2 on 2021-03-25 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_remove_aluno_cpf2'),
        ('validacpfs', '0003_remove_validacpf_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacpf',
            name='aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.Aluno'),
        ),
    ]
