# Generated by Django 2.2 on 2021-03-25 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('validacpfs', '0004_validacpf_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacpf',
            name='Professor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professores.Professor'),
        ),
    ]
