# Generated by Django 3.1.7 on 2021-03-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacpfs', '0005_validacpf_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidaCpf',
        ),
    ]
