# Generated by Django 3.1.7 on 2021-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracao',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='data',
            field=models.DateField(max_length=8, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='administracao',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
    ]
