# Generated by Django 2.2 on 2021-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('ID_Turma', models.AutoField(primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=45)),
                ('modalidade', models.CharField(choices=[('Adolescentes', 'Adolescentes'), ('Adulto', 'Adulto'), ('Infantil', 'Infantil'), ('Jovens', 'Jovens'), ('Juvenis', 'Juvenis'), ('Pré-Adolescentes', 'Pré-Adolescentes')], max_length=100)),
            ],
        ),
    ]
