# Generated by Django 3.1.7 on 2021-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('ID_Turma', models.AutoField(primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=45)),
            ],
        ),
    ]
