# Generated by Django 3.1.7 on 2021-03-18 01:11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.CharField(choices=[('Infantil', 'Infantil'), ('Pré Adolescentes', 'Pré Adolescentes'), ('Adolescentes', 'Adolescentes'), ('Juvenis', 'Juvenis'), ('Jovens', 'Jovens'), ('Adulto', 'Adulto'), ('Novos Convertidos', 'Novos Convertidos')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
