# Generated by Django 3.1.7 on 2021-03-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.CharField(choices=[('Adolescentes', 'Adolescentes'), ('Adulto', 'Adulto'), ('Infantil', 'Infantil'), ('Jovens', 'Jovens'), ('Juvenis', 'Juvenis'), ('Pré-Adolescentes', 'Pré-Adolescentes')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
