# Generated by Django 3.1.7 on 2021-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='Professor',
            field=models.ManyToManyField(to='professores.Professor'),
        ),
    ]
