# Generated by Django 3.1.7 on 2021-03-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0002_turma_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='Professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='Professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professores.professor'),
            preserve_default=False,
        ),
    ]
