# Generated by Django 3.1.7 on 2021-03-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_auto_20210317_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='Professor',
        ),
    ]
