# Generated by Django 3.1.7 on 2021-03-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0002_turma_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ID_Professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
        ),
    ]
