# Generated by Django 3.1.7 on 2021-05-18 18:45

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=cpf_field.models.CPFField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.IntegerField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='data',
            field=models.DateField(max_length=8),
        ),
    ]
