# Generated by Django 3.1.7 on 2021-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_auto_20210518_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
