# Generated by Django 3.1.7 on 2021-05-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_professor_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
    ]
