# Generated by Django 3.1.7 on 2021-05-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0005_auto_20210527_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data',
            field=models.DateField(max_length=8, verbose_name='Data de Nascimento'),
        ),
    ]
