# Generated by Django 2.2 on 2021-03-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacpfs', '0001_initial'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='validacpfs.ValidaCpf'),
            preserve_default=False,
        ),
    ]
