# Generated by Django 3.1.7 on 2021-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
