# Generated by Django 2.2 on 2021-03-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validacpfs', '0003_remove_validacpf_aluno'),
        ('alunos', '0003_remove_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='validacpfs.ValidaCpf'),
        ),
    ]
