# Generated by Django 2.2 on 2021-03-25 02:18

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf2',
            field=cpf_field.models.CPFField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
