# Generated by Django 2.2 on 2021-03-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_auto_20210324_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf2',
        ),
    ]
