# Generated by Django 3.1.7 on 2021-03-25 16:29

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_remove_aluno_cpf2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=cpf_field.models.CPFField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
