# Generated by Django 3.1.7 on 2021-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
