# Generated by Django 3.1.7 on 2021-03-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_auto_20210325_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(default=1, upload_to='alunos'),
            preserve_default=False,
        ),
    ]
