# Generated by Django 3.1.7 on 2021-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_remove_aluno_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.FileField(default=1, upload_to='media/%y'),
            preserve_default=False,
        ),
    ]
