# Generated by Django 3.1.7 on 2021-03-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_auto_20210326_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='imagem',
        ),
    ]
