# Generated by Django 3.1.7 on 2021-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_remove_aluno_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(max_length=16),
        ),
    ]
