# Generated by Django 3.1.7 on 2021-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_auto_20210326_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.IntegerField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
