# Generated by Django 3.1.7 on 2021-03-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_auto_20210329_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
