# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_auto_20210329_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='municipio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
