# Generated by Django 3.1.7 on 2021-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_aluno_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
