# Generated by Django 3.1.7 on 2021-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0020_auto_20210329_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/%y'),
        ),
    ]
