# Generated by Django 3.1.7 on 2021-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_auto_20210329_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(default=1, upload_to='media/%y'),
            preserve_default=False,
        ),
    ]
