# Generated by Django 3.1.7 on 2021-04-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0023_auto_20210330_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='imagem',
        ),
    ]
