# Generated by Django 3.1.7 on 2021-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0024_remove_aluno_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imageAluno',
            field=models.ImageField(default=1, upload_to='img/%y'),
            preserve_default=False,
        ),
    ]
