# Generated by Django 3.1.7 on 2021-05-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0025_aluno_imagealuno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='imageAluno',
            new_name='image',
        ),
    ]
