# Generated by Django 3.1.7 on 2021-05-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0026_auto_20210517_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='image',
            new_name='imagem',
        ),
    ]
