# Generated by Django 3.1.7 on 2021-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0027_auto_20210517_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Deficiencia',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='RestricaoAlimentar',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nomeResp',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefoneResp',
            field=models.IntegerField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
