# Generated by Django 3.1.7 on 2021-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0028_auto_20210518_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Medicamento',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='Saude',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
