# Generated by Django 3.1.7 on 2021-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0029_auto_20210518_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Deficiencia',
            field=models.CharField(max_length=100, verbose_name='Tem alguma deficiência?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='Medicamento',
            field=models.CharField(max_length=100, verbose_name='O aluno toma algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='RestricaoAlimentar',
            field=models.CharField(max_length=100, verbose_name='Alguma alergia ou restrição alimentar?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='Saude',
            field=models.CharField(max_length=100, verbose_name='Possui algum problema de saúde?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nomeResp',
            field=models.CharField(max_length=45, verbose_name='Em caso de emergência entrar em contato com?'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefoneResp',
            field=models.IntegerField(max_length=16, verbose_name='Telefone do responsável'),
        ),
    ]
