# Generated by Django 3.1.7 on 2021-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0030_auto_20210518_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(max_length=11),
        ),
    ]
