# Generated by Django 3.1.7 on 2021-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0032_auto_20210526_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
