# Generated by Django 3.1.7 on 2021-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0033_auto_20210526_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefoneResp',
            field=models.CharField(max_length=11, verbose_name='Telefone do responsável'),
        ),
    ]
