# Generated by Django 3.1.7 on 2021-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0034_auto_20210526_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefoneResp',
            field=models.CharField(max_length=13, verbose_name='Telefone do responsável'),
        ),
    ]
