# Generated by Django 3.1.7 on 2021-06-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0035_auto_20210527_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
    ]
