# Generated by Django 3.1.7 on 2021-03-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='data',
        ),
    ]
